_:
    EnableClient: True
    EnableServerCpp: True
    EnableServerGo: True
    EnableBlueprint: True

EEnumType:
    _: "Test Enum" #此为导出时枚举值的注释
    EEnumType_Type_0:
    EEnumType_Type_1: 2 #支持指定Value值，指定后，后续值在此基础上+1
    EEnumType_Type_Max:

EEnumType2:
    EEnumType2_Type_None:
    EEnumType2_Type_1: 1
    EEnumType2_Type_Max:

EEnumType3:
    EEnumType3_Type_None:
    EEnumType3_Type_1:
    EEnumType3_Type_Max:
