ETestType:
    _: "Test Enum" #此为导出时枚举值的注释
    ETestType_Type_0:
    ETestType_Type_1: 2 #支持指定Value值，指定后，后续值在此基础上+1
    ETestType_Type_Max:

ETestType2:
    ETestType2_Type_None:
    ETestType2_Type_1: 1
    ETestType2_Type_Max:
